### PR TITLE
fix flat list

### PR DESCRIPTION
**Pull request by AviAvni**
flat list is work with this change also I added the rest of the properties I'll check them later

### CODE REVIEW

**Comment by AviAvni** [comment]
I ported the missing types

**Review by forki — APPROVED** [review]
Lgtm

**Comment by forki** [comment]
@alfonsogarciacaro I'm probably not able to merge/release it anytime soon. But I'm probably able to review PRs from phone. I think this one is good for release. So if you find time then please go ahead...

**Comment by MangelMaxime** [comment]
@forki If you want I can release it ?

**Comment by MangelMaxime** [comment]
In version `1.3.0-alpha002` ? Just asking if we keep the alpha version for now ?

**Comment by forki** [comment]
The alpha is because of backandroid incompatibilities. Yes please do alphas
for now


Am 02.08.2017 10:13 schrieb "Maxime Mangel" <notifications@github.com>:

**Comment by MangelMaxime** [comment]
Ok, I am doing the merge and releasing the version now.

**Comment by MangelMaxime** [comment]
Available in [Fable.React.Native 1.3.0-alpha002](https://www.nuget.org/packages/Fable.React.Native/1.3.0-alpha002)

**Pull request merged**
