### PR TITLE
port react-native-video

### PR DESCRIPTION
**Pull request by AviAvni**
When I worked on the flat list coping the source to 
fable-react_native-demo\packages\Fable.React.Native\fable
and the dll to fable-react_native-demo\packages\Fable.React.Native\lib\netstandard1.6 
the intelisense didn't work but the compilation work ok
working on this code coping the source and the dll on build the fable compiler didn't compile the new files
How I can check if this code work?

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
An easy way to test changes locally is probably just adding a `ProjectReference` to the library source ([example](https://github.com/fable-compiler/fable-import/blob/f77c8e11db1e66a6f07572e2e4d5b520dbb500d2/Express/Fable.Import.Express.fsproj#L11)). I think @MangelMaxime uses Paket local dependencies but I haven't used them yet.

**Comment by AviAvni** [comment]
@alfonsogarciacaro @MangelMaxime @forki 
I checked this and this code is working 
when this merged it I'll add sample to fable-react_native-demo

**Comment by alfonsogarciacaro** [comment]
Sorry for the late response @AviAvni, I just came back from vacation 😎 

Let's merge this and I'll publish a new version right away. Thanks a lot your contribution!

**Comment by alfonsogarciacaro** [comment]
Published as Fable.React.Native.1.3.0-alpha003 :+1:

**Pull request merged**
