### PR TITLE
ViewPager has moved

### PR DESCRIPTION
**Pull request by forki**
/cc @MangelMaxime

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Do you want me to merge and release?

**Comment by forki** [comment]
yes please, but the question is if we should separate it as well at some point

**Comment by MangelMaxime** [comment]
What do you mean by `separate`?  

Are `@react-native-community/` and `react-native` a different packages?

**Comment by forki** [comment]
Yes they extracted a lot of the core features into separate packages to
have a smaller core

Maxime Mangel <notifications@github.com> schrieb am Di., 12. März 2019,
18:02:

**Comment by MangelMaxime** [comment]
Then indeed IMHO it's better to split the package. 

We can remove completely the Helper or let it mark it as `Obselete` to help people migrate. If we mark it as `Obselete` we can let the old implementation in place so the transition is smoother or just use `jsNative` to force people to migrate.

**Comment by forki** [comment]
I think for now I'd go with keeping it - at least until I found all the
packages that were removed.

Maxime Mangel <notifications@github.com> schrieb am Di., 12. März 2019,
19:41:

**Comment by forki** [comment]
Ok I removed ViewPager and AsyncStorage from the main package

**Pull request merged**
