### PR TITLE
Animated view

### PR DESCRIPTION
**Pull request by thitemple**
I was trying to create some animations and realized I could not create the Animated components so I added these to the typings.

Please let me know if it is good enough, and any changes needed. 

Also, how do you test this locally? When I build it with FAKE there is no usable output, what am I missing. Thanks.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Looks good, there should be no problems to merge. TBH, I haven't really used ReactNative so we don't really test things 😅 I'm just hoping that @forki is having a look and making sure everything works fine :wink:

**Comment by thitemple** [comment]
Yeah, I copied the Fable.Helpers.ReactNative and Fable.Import.ReactNative files into my project and tested them from there. I have some adjustments and I will push them tomorrow. 

I will also use your suggestion for the Object.assign and push that as well. All my changes are related to RN animations.

**Comment by iyegoroff** [comment]
Hi, @thitemple , do you have something else to push or this can be merged as is?

**Comment by forki** [comment]
ok I merged it and upgraded it to the Fable.Core 3 - you can use 2.0.0-beta-013

**Pull request merged**
