### PR TITLE
various fixes

### PR DESCRIPTION
**Pull request by iyegoroff**
- fixed `FlatList` prop case conversion;
- added `SectionList`;

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks! Please let me know when you want a new release of this... or maybe I should just make you a collaborator of the Nuget package as you've basically written all the new code of latest releases. Would you be interested?

**Comment by iyegoroff** [comment]
> I should just make you a collaborator of the Nuget package

Yes, please, that would be great.
Aslo would it be possible to publish a Nuget release from OSX?

**Comment by MangelMaxime** [comment]
Yes you can. I mean i am using Linux and OS X only and so publish all the package from it

**Comment by alfonsogarciacaro** [comment]
Awesome, I sent you invitations for write access to this repo and sharing ownership of the Nuget package, @iyegoroff. I'm always publishing from macOS, so you should be able to do it as well :)

1. Add your Nuget key to an environmental variable named `NUGET_KEY` (only once or use FAKE CLI to pass it through the arguments each time).
2. Edit `RELEASE_NOTES.md` to add a new version on top and the changes included.
3. Run the FAKE GithubRelease target (e.g. `sh build.sh GithubRelease`). This will put the version on top of RELEASE_NOTES in the .fsproj, publish the Nuget package and create a commit to tag and push the current code to Github releases.

> If for some reason you want to publish a new Nuget package but don't want a GH release, run the "PublishPackages" target instead.

I hope it works for you. After accepting the two invitations you can give it a try to see if you can publish a new version. Contact me if you have any problem.

Thanks a lot for all your contributions and welcome to the team!

**Pull request merged**
