### PR TITLE
Geotype

### PR DESCRIPTION
**Pull request by thitemple**
This will add types to the GeolocationReturnType. 

Base on the RN documentation, it is extending the Browser's Geolocation API so it returns this:

https://developer.mozilla.org/en-US/docs/Web/API/Position

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks @thitemple! Apparently a mysterious (and big) file sneaked into the PR (src/Fable.Import.ReactNative.fs.orig). Can you please remove it?

**Comment by thitemple** [comment]
Done, sorry about that

**Comment by alfonsogarciacaro** [comment]
NP, thank you! 😸

**Comment by alfonsogarciacaro** [comment]
I forgot the latest version is an alpha version, so I published the new one as 2.0.0-alpha-002 (meaning you need to add `prerelease` in paket.dependencies to download it). Is that OK for you?

**Comment by thitemple** [comment]
That's how I have it right now ;)
Thanks

**Pull request merged**
