### PR TITLE
Update to Fable 2.0

### LINKED ISSUE #39: Fable 2.0 support
Hello,

I was wondering if there were plans to get this library up to date with the newest Fable 2.0
Otherwise I will start looking into what is needed to get this working.

Thanks

### PR DESCRIPTION
**Pull request by forki**
fixes #39

@alfonsogarciacaro any chance you can take a look and release it? I really want to move my RN project to fable 2 - so that I don't need to bug you about bugs in fable 1.x :P

/cc @MangelMaxime

### CODE REVIEW

**Comment by MangelMaxime** [comment]
@forki Latest version of Fable.React.Native is 2.0.0-alpha-014 should I release it as 2.0.0-alpha-015 or 3.0.0-alpha-001 ?

**Comment by forki** [comment]
How about 2.0 proper?

Am Mi., 20. Feb. 2019, 11:11 hat Maxime Mangel <notifications@github.com>
geschrieben:

**Comment by MangelMaxime** [comment]
I was proposing v3 because v2 alpha was for Fable 1.x support.

@forki Is it working or do we need an alpha/beta version first?

**Comment by forki** [comment]
I don't know yet
so yes alpha would be good

**Comment by MangelMaxime** [comment]
@forki I fixed the errors and warnings but I didn't test the project. I don't have a RN app and never created one 😊

Now we need to wait after nuget

**Comment by forki** [comment]
thanks! the question now is: how to do the rest of https://github.com/SAFE-Stack/SAFE-Nightwatch/issues/64 - Imean we don't have webpack here

**Pull request merged**
