### PR TITLE
Update Fable.Helpers.ReactNative.SimpleStore.DB.fs

### PR DESCRIPTION
**Pull request by forki**
I tried to fix compile errors but still having trouble with the Thoth decoder.

image

### CODE REVIEW

**Comment by forki** [comment]
ah found it

**Comment by forki** [comment]
ok this is ready for beta002

**Comment by MangelMaxime** [comment]
Ah yes, I knew I was missing something.

**Comment by MangelMaxime** [comment]
Released as beta003 

*beta002 was released without pulling master before 🤦‍♂️*

**Pull request merged**
