### PR TITLE
Add a button

### PR DESCRIPTION
**Pull request by forki**
@alfonsogarciacaro hugs!

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Done! BTW, you are also an owner of the nuget package, so you should be able to publish new versions if you need them fast. Just edit RELEASE_NOTES and run `build.cmd GithubRelease` (the script expects a `NUGET_KEY` env var).

**Comment by forki** [comment]
got it. thanks

**Comment by forki** [comment]
that nuget_key env variable is a dangerous thing - would love to pass it by command line arg instead

**Comment by forki** [comment]
ok passing from cmd line works but I get PUT methodnotallowed from dotnet nuget push

Why are you not pushing with paket?

**Comment by alfonsogarciacaro** [comment]
Hmm, that's weird. Paket push was giving problems (I think we already talked about that in a couple of other GH issues but don't remember where) and I changed it to dotnet push and it was working, so...

**Comment by forki** [comment]
what problems? I seriously never had one.

**Comment by alfonsogarciacaro** [comment]
https://github.com/fable-compiler/fable-import/issues/33

**Pull request merged**
